### ISSUE TITLE
Groll list is not updated when commits are added

### ISSUE THREAD

**Issue by diversit** [sbt/sbt-groll#11]
With an sbt session open, after adding commits to the 'groll' branch via command-line git, SourceTree or IDE, then running 'groll show' does not show the newest commits. It does not show any active commit (with '==').

When you do 'groll show' it shows the commit you last went to using groll, but this should be the current commit which is newer.
When you do 'groll head', groll moves the 'groll' branch to the 'git show' commit.
When you then do 'git log' in a separate terminal, the new commits seems to have been lost. Luckily they can be restored via the git reflog.

Groll should be aware of new commits on the 'groll' branch. 
Show command should correctly point to the latest commit. 
List command should display the new commits.

**Comment by diversit** [comment]
When you add the new commits to the 'master' branch, then 'groll show' and 'groll list' show the actual current commit and the full commit list including the new commits.
However, 'groll head' says you're already at the head of the commit history, but the 'groll' branch is not forwarded to the latest commit on master.

'groll next' does nothing, because it thinks it is already at head (just like 'head' command).
'groll prev' moves to the 'groll' branch to the commit before the latest commit on master. 

So, when 'groll' branch is on commit 1, and master branch already has commits 2 and 3.
Then 'groll list' correctly shows all commits and shows commit 3 as current, but the 'groll' branch still points to commit 1.
Doing 'groll next' does nothing.
Doing 'groll prev' moves the 'groll' branch to commit 2.
You can then do a 'groll next' which moves the 'groll' branch to commit 3.

**Comment by hseeberger** [comment]
Thanks for reporting. As you have already found out, the "groll" branch is not for tracking the actual history, but it's the "workingBranch" (the name can be configured with the "workingBranch" setting), i.e. the branch to roll through the commits.

Wrt to changes to the "historyRef" branch, which by default is master, let me point out that sbt-groll has never been intended for live changes to the history branch. Currently I don't have the time to add this, but PRs are welcome.

**Comment by hseeberger** [comment]
Closing because no more activity.
