### ISSUE TITLE
4.6.0 not available from default repos

### ISSUE THREAD

**Issue by johanandren** [sbt/sbt-groll#12]
Following the instructions I get resolution error for 4.6.0 from sbt (4.5.0 is available from bintray though).

**Comment by hseeberger** [comment]
Looks like sbt-groll is only published to the old community repo, not to Bintray. Sigh!
Thanks for reporting!

**Comment by hseeberger** [comment]
Should be fixed now. @johanandren, could you please give it another try?

**Comment by johanandren** [comment]
Works fine now. Thanks!
